name: jbang
version: 0.85.1
summary: Unleash the power of Java
description: |
  Unleash the power of Java.
  Use `jbang` to run java, jar, jsh or kt file(s) with automatic dependency fetching
  and immediate compilation and execution.

grade: stable
confinement: classic
base: core18
type: app

apps:
  jbang:
    command: bin/jbang

parts:
  jbang:
    plugin: dump
    source: https://github.com/jbangdev/jbang/releases/download/v0.85.1/jbang-0.85.1.tar
    source-checksum: sha256/dd4e6aab19c8726fb0ff279aea5bb5925f4ce31679293438e62f19c14fe19d4c
    stage-packages:
      - curl
