name: jbang
version: 0.117.1
summary: Unleash the power of Java
description: |
  Unleash the power of Java.
  Use `jbang` to run java, jar, jsh or kt file(s) with automatic dependency fetching
  and immediate compilation and execution.

grade: stable
confinement: classic
base: core18
type: app

apps:
  jbang:
    command: bin/jbang

parts:
  jbang:
    plugin: dump
    source: https://github.com/jbangdev/jbang/releases/download/v0.117.1/jbang-0.117.1.tar
    source-checksum: sha256/c2a8e2d4879e32e63e545892a7e06be4ca6e90be38d1d690086847d7c684d579
    stage-packages:
      - curl
