name: jbang
version: 0.139.3
summary: Unleash the power of Java
description: |
  Unleash the power of Java.
  Use `jbang` to run java, jar, jsh or kt file(s) with automatic dependency fetching
  and immediate compilation and execution.

grade: stable
confinement: classic
base: core26
type: app

apps:
  jbang:
    command: bin/jbang

parts:
  jbang:
    plugin: dump
    source: https://github.com/jbangdev/jbang/releases/download/v0.139.3/jbang-0.139.3.tar
    source-checksum: sha256/e7d4bbae0f7321fb8fe7033db7e01b8729f5385103c6445e90b82ace87f652f6
    stage-packages:
      - curl
