name: jbang
version: 0.122.0
summary: Unleash the power of Java
description: |
  Unleash the power of Java.
  Use `jbang` to run java, jar, jsh or kt file(s) with automatic dependency fetching
  and immediate compilation and execution.

grade: stable
confinement: classic
base: core18
type: app

apps:
  jbang:
    command: bin/jbang

parts:
  jbang:
    plugin: dump
    source: https://github.com/jbangdev/jbang/releases/download/v0.122.0/jbang-0.122.0.tar
    source-checksum: sha256/66c989c73ef7e191672a29dd4d6b77cd8f348d398c43a5b2374f8ff9c9047b8b
    stage-packages:
      - curl
