name: jbang
base: core18 # the base snap is the execution environment for this snap
version: '0.67.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: run java as scripts with a bang # 79 char long summary
description: |
  jbang let you build and run java applications without java pre-installed
  and using any dependency for your scripts/apps.

grade: stable
confinement: classic

apps:
  jbang:
    command: bin/jbang

parts:
  jbang:
    # See 'snapcraft plugins'
    plugin: dump
    source: https://github.com/jbangdev/jbang/releases/download/v0.67.1/jbang-0.67.1.tar
    stage-packages: 
      - curl