name: jbang
version: 0.138.0
summary: Unleash the power of Java
description: |
  Unleash the power of Java.
  Use `jbang` to run java, jar, jsh or kt file(s) with automatic dependency fetching
  and immediate compilation and execution.

grade: stable
confinement: classic
base: core26
type: app

apps:
  jbang:
    command: bin/jbang

parts:
  jbang:
    plugin: dump
    source: https://github.com/jbangdev/jbang/releases/download/v0.138.0/jbang-0.138.0.tar
    source-checksum: sha256/2b83d1322215b597a1a3e9918d8052737f579d70b9f342521be52c9e3013fd0e
    stage-packages:
      - curl
