name: jbang
version: 0.140.1
summary: Unleash the power of Java
description: |
  Unleash the power of Java.
  Use `jbang` to run java, jar, jsh or kt file(s) with automatic dependency fetching
  and immediate compilation and execution.

grade: stable
confinement: classic
base: core18
type: app

apps:
  jbang:
    command: bin/jbang

parts:
  jbang:
    plugin: dump
    source: https://github.com/jbangdev/jbang/releases/download/v0.140.1/jbang-0.140.1.tar
    source-checksum: sha256/c396840221103902693c69a159ca91737cfdede24780550921f2bd5ac3be2f53
    stage-packages:
      - curl
