name: jbang
version: 0.126.3
summary: Unleash the power of Java
description: |
  Unleash the power of Java.
  Use `jbang` to run java, jar, jsh or kt file(s) with automatic dependency fetching
  and immediate compilation and execution.

grade: stable
confinement: classic
base: core18
type: app

apps:
  jbang:
    command: bin/jbang

parts:
  jbang:
    plugin: dump
    source: https://github.com/jbangdev/jbang/releases/download/v0.126.3/jbang-0.126.3.tar
    source-checksum: sha256/09177b6f0d50b8c2ff081fe23008c25790a6dcd365cb9662772fbd480bd7255e
    stage-packages:
      - curl
