on:
    push:
        branches:
            - master
        tags:
            - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: snapcore/action-build@v1
      id: build
      with:
        path: snap
    - uses: snapcore/action-publish@v1
      id: publish
      with:
        store_login: ${{ secrets.STORE_LOGIN }}
        snap: ${{ steps.build.outputs.snap }}
        release: edge