on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: snapcore/action-build@v1
        id: build
        with:
          snapcraft-channel: beta
      - uses: actions/upload-artifact@v7
        with:
          name: snap
          path: ${{ steps.build.outputs.snap }}
      - uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: edge
